services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 5s
      retries: 10

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    volumes:
      - redis_data:/data
    networks:
      - inception
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - DOMAIN=${DOMAIN}
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file:
      - .env
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: always

  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    env_file:
      - .env
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "2121:21"
      - "60000-60010:60000-60010"
    restart: always

  website:
    container_name: website
    build: ./requirements/bonus/website
    networks:
      - inception
    ports:
      - "5000:5000"
    restart: always

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    networks:
      - inception
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
   
  phpmyadmin:
    container_name: phpmyadmin
    build: ./requirements/bonus/phpmyadmin
    networks:
      - inception
    ports:
      - "8081:8081"
    restart: always

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/haaghaja/data/db/
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/haaghaja/data/wp/
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/haaghaja/data/redis/

networks:
  inception:
    driver: bridge
